### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by octopus-prime** [cpp-testing/GUnit#10]
[linux.txt](https://github.com/cpp-testing/GUnit/files/1170468/linux.txt)
[osx.txt](https://github.com/cpp-testing/GUnit/files/1169891/osx.txt)
Documentation says:

```
$mkdir build && cd build && cmake ..
$make && ctest
```

- Does not build on OSX 10.12 (using clang 8.1.0).
- Does not build on Ubunu 17.04 (using gcc 7.0.1).

**Comment by krzysztof-jusiak** [comment]
Fixed by https://github.com/cpp-testing/GUnit/commit/f53fd8db681bea7f179a82a6feb148bab86e28de
