### ISSUE TITLE
arguments containing whitespace cannot be fully captured

### ISSUE THREAD

**Issue by zsolttabi** [cpp-testing/GUnit#24]
when capturing a string with multiple words separated by spaces the captured variable only contains the first word

for example:
capturing this:
Given I type the following: 'this is a complex command'
with this:
Given("I type the following: '{command}'") = [] (std::string command) {
    std::cout << command;
};
outputs the following:
this

**Comment by krzysztof-jusiak** [comment]
Closing as it got fixed by @zsolttabi, thanks
