### ISSUE TITLE
Update to googletest 1.10.x

### ISSUE THREAD

**Issue by thorsten-klein** [cpp-testing/GUnit#32]
Hello,
is there anyone working on gunit regarding integration of googletest 1.10.0?
Link: https://github.com/google/googletest/releases/tag/release-1.10.0

Best Regards,
thorsten

**Comment by toresbe** [comment]
This was a bit of a pain in the tuches for me, as it took me a while to realize why the MOCK_METHOD macro from all of Google's docs weren't working :)

I tried simply fetching HEAD from googletest in the tree, but then gunit won't build.

**Comment by thorsten-klein** [comment]
Hello @toresbe ,
so you also do not have any solution for the usage with googletest 1.10.x?

We were only able to adapt gunit to be compatible with googletest 1.8.1 but it would be interesting if someone has integrated googletest 1.10.x
