### ISSUE TITLE
Heavy

### ISSUE THREAD

**Issue by phcerdan** [cpp-testing/GUnit#8]
Hi, the repo weights 111.56 MB, not the best if I want to download it as an ExternalProject in cmake.

I will copy the include folder into my project by now, but you might want to have a look!
Nice work btw, thanks!

**Comment by krzysztof-jusiak** [comment]
Thanks, @phcerdan for pointing that out. I looked around a bit and find out it's because I pulled https://github.com/nlohmann/json library which took most space of those 111.56 MB.
I'm not sure I can do much about it without rewriting the git history, though? Any ideas?

**Comment by Fazer2** [comment]
What was the reason of including a copy of the json project in this repository? Did it require changes to work with GUnit? If it can be removed, I would bite the bullet and erase it from this repo history while it's still fairly new.

**Comment by krzysztof-jusiak** [comment]
Fixed, GUnit weight 18Mbn now. json is still used as a submodule (only needed for BDD style tests, though).
