### ISSUE TITLE
Request: New gunit release 1.13.0

### ISSUE THREAD

**Issue by thorsten-klein** [cpp-testing/GUnit#86]
After the submodule of googletest has been updated to v1.13.0 by PR #85 it would be nice to create a official GUnit release.
I would suggest to release current master commit as v1.13.0.
For users it might be helpful/transparent that the gunit version is equivalent to its underlaying gtest version (at least MAJOR.MINOR).

**Comment by krzysztof-jusiak** [comment]
https://github.com/cpp-testing/GUnit/releases/tag/v1.13.0
